### ISSUE TITLE
your citibike project

### ISSUE THREAD

**Issue by fedhere** [sunglyoungKim/PUI2017_sk6176#2]
your citiike project idea is forumalted in a confusing way in the verbal english sttement as well as in the formula, where you are missing some pieces of the equation
'''

IDEA: Women has short trip duration of usage of citibike than men.
NULL HYPOTHESIS:
The women's trip duration that use of citi-bike is the same or higher than the men's trip duration of usage of the bike.
_$H_0$_ : frequency of Women's trip duration < frequency of Men's trip duration
_$H_1$_ : frequency of Women's trip duration >= frequency of Men's trip duration
or identically:
_$H_0$_ : frequency of Women's trip duration - frequency of Men's trip duration < 0
_$H_1$_ : frequency of Women's trip duration - frequency of Men's trip duration >= 0

make sure you fix it before proceeding to the analysis!

**Comment by sunglyoungKim** [comment]
Hello, I have fixed it and uploaded on HW7 for update version

Thank you

**Comment by sunglyoungKim** [comment]
IDEA: Women has short trip duration of usage of citibike than men.
NULL HYPOTHESIS:
The women's trip duration that use of citi-bike is the same or higher than the men's trip duration of usage of the bike.
_$H_0$_ : frequency of Women's trip duration < frequency of Men's trip duration
_$H_1$_ : frequency of Women's trip duration >= frequency of Men's trip duration
or identically:
_$H_0$_ : frequency of Women's trip duration - frequency of Men's trip duration < 0
_$H_1$_ : frequency of Women's trip duration - frequency of Men's trip duration >= 0
